[package]
name = "rink-runtime"
version = "0.1.0"
edition = "2021"
authors = ["Florent Veilly"]

[dependencies]
colored = "2.0"
rstest = "0.18"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
